// pages/_app.tsx

import type { AppProps } from 'next/app';
import type { Metadata } from "next";
import { Spectral, Spectral_SC, Open_Sans, IBM_Plex_Serif, Roboto_Mono, Merriweather, Merriweather_Sans, Playfair_Display, Playfair_Display_SC, Space_Mono } from "next/font/google";
import Head from 'next/head';
import { GA_MEASUREMENT_ID, pageview } from '@/lib/gtag';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Script from 'next/script';
import { ThemeProvider } from '@/ThemeContext';

import "../globals.css";


{/* <meta name="description" content="Like a mirror for your voice"> */}


const spectral = Spectral({
  variable: "--spectral",
  weight: '400',
  subsets: ['latin']
});

const spectralSC = Spectral_SC({
  variable: "--spectral-sc",
  weight: '800',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const jsonLd = {
//   "@context": "https://schema.org",
//   "@type": "Person",
//   "name": "Ada Lovelace",
//   "url": "https://adalovelace.dev",
//   "sameAs": [
//     "https://twitter.com/ada",
//     "https://github.com/ada"
//   ]
// };


export default function App({ Component, pageProps }: AppProps) {


  const router = useRouter();

  useEffect(() => {
    const handleRouteChange = async (url:string) => {
      await pageview(url);
    };

    router.events.on('routeChangeComplete', handleRouteChange);

    // For initial page load:
    pageview(window.location.pathname);

    return () => {
      router.events.off('routeChangeComplete', handleRouteChange);
    };
  }, [router.events]);


  const [gtagLoaded, setGtagLoaded] = useState(false);

  return <main className={ ' ' +spectralSC.variable}>
      <>
        {/* Google Analytics */}
        {/* <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
        /> */}

      <Script
        strategy="afterInteractive"
        
        src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
        onLoad={() => {
          setGtagLoaded(true);
          console.log('GA script loaded');
        }}
      />


      {gtagLoaded && (
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              window.gtag = gtag;
              gtag('js', new Date());
              gtag('config', '${GA_MEASUREMENT_ID}', {
                page_path: window.location.pathname,
              });
            `,
          }}
        />
      )}        
        {/* Ads
        <script async src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`} />
        <script dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_MEASUREMENT_ID}');
          `
        }} /> */}



        {/* <link rel="icon" type="image/svg+xml" href="/block.svg" /> */}


        {/* Favicon */}
        <link rel="icon" href="/block.svg" />

      </>
      <ThemeProvider>
        <Component {...pageProps} />
      </ThemeProvider>
    </main>
}

